mattn/go-oci8

oci8.go, oci8_test.go
=> Fix #45 - DSN parsing to allow TNS Names lookup

oci8.go
See individual commits.
Regards,
Jamil Djadala
=> various fixes & improvements

oci8.go
=> more changes

dsn.go, oci8.go, oci8_test.go
=> parse environment once, partial modified copy of net/url

oci8.go
=> remove usage of finalizers

oci8.go
That says it all. Thanks in advance!
=> Actually provide a formatted string when calling fmt.Errorf

oci8.go
=> OCI_SUCCESS_WITH_INFO is right

oci8.go
Hit this code with a nil rows in the Query function 
`rows.(*OCI8Rows).cls = true`
=> Unchecked error in query fixed

oci8.go, oci8_go18.go, oci8_go18_test.go
anyone, could you please try this feature?
cc: @djadala
=> support output parameters

oci8.go
Hi,
I think ORA-12528 also is 'driver.ErrBadConn',
Regards,
Jamil Djadala
=> added ORA-12528 to bad connections

oci8.go
=> added ORA-12537, ORA-01033, ORA-01034 to badConnCodes

_example/as_sysdba/main.go, oci8.go, oci8_test.go
Here are the changes to allow "as sysdba/sysoper" kind of connections: 
sys/syspwd@host:1521/ORCL?loc=America%2FLos_Angeles as sysdba
=> add support for "as sysdba/sysoper" connections

oci8.go
There is a race condition that shows up when you `defer cancel()` a context.
The go-routine that handles context timeouts might not get scheduled quickly enough, and might not get scheduled before the results have been returned, resulting in both the rows.done channel and the ctx.Done channel being ready.  Golang's `select` chooses randomly, and will often result in the database connection or session being broken, even though valid results have already been returned.  This results in the next query getting cancelled before it can even begin.
This happens to me quite often, and I was able to reproduce the issue on colleague's laptop and with a docker setup.
Rough reproduction:
```go
func allThings(conn *sqlx.DB) error {
for {
things, err := getThings(conn)
if err != nil {
return err
}
for …
```
=> fix race condition when query/exec is done and context is too

oci8.go, oci8_go18_test.go, oci8_go19_test.go
based on https://github.com/mattn/go-oci8/pull/201
=> Added uint64 casting for sql.Out{}.

README.md
=> Add MacOS example

oci8.go
If you want to use external authentication (os level or LDAP), you need
to tell the API to exactly do that.
This patch tries to implement this the common way of not having a
username, a password and a host to connect an. In that case, the
external authentication is triggered and the credentials are changed
in the OCI8 C API to external (OCI_CRED_EXT).
(based on this issue #209)
=> Enabling real external authentication

_example/as_sysdba/main.go
Adding more descriptive text how to use it and externalize DSN to the
command line.
=> Externalize DSN

oci8.go
=> Fix cancelation

more_test.go, oci8.go
=> Minor cleanup

more_test.go, oci8Sql_test.go, oci8_test.go, statement.go
=> Added TestDestructiveNumber

connection.go, globals.go, more_test.go, oci8.go, oci8Sql_test.go, rows.go, statement.go
Added CLOB & NCLOB tests
Added OCILobCharSetForm
Added sizeOfNilPointer
Using OCI OCILobRead needs argument saying if it is a SQLCS_IMPLICIT (CLOB) or SQLCS_NCHAR (NCLOB). Added OCI call to OCILobCharSetForm to get that value.
=> Fixed NCLOB

connection.go, connector.go, globals.go, oci8.go, oci8Sql_test.go, oci8_go18.go
=> Added driver logger

connection.go, globals.go, more_test.go, oci8.go, oci8Sql_test.go, rows.go, statement.go
Added BLOB tests
Added INTERVAL DAY TO MONTH tests
Added INTERVAL DAY TO SECOND tests
=> Added tests

connection.go, dsn.go, globals.go, oci8.go, oci8SqlTime_test.go, oci8_go18.go, oci8_test.go, rows.go, statement.go
=> Added Tests, changed away from unsafe.Pointer

oci8.go, oci8SqlNumber_test.go, oci8Sql_test.go, oci8_test.go, rows.go, statement.go
Fix outputBoundParameters for float
Added testRunExecResults and testRunExecResult
Added TestFunctionCallNumber
=> Added function tests, fix out for float

cHelpers.go, connection.go, oci8.go, oci8.go.h, oci8SqlNumber_test.go, oci8SqlString_test.go, oci8SqlTime_test.go, oci8Sql_test.go, oci8_test.go, rows.go, statement.go, test.sh
Added ociAttrGetStmt
Added ociAttrGetParam
Removed WrapOCIAttrGetUb2
=> Switch from WrapOCIAttrGetUb2 to ociAttrGetX

cHelpers.go, connection.go, globals.go, oci8.go, oci8.go.h, oci8SqlNumber_test.go, oci8SqlString_test.go, oci8SqlTime_test.go, oci8Sql_test.go, rows.go, statement.go, test.sh
After https://github.com/mattn/go-oci8/pull/274
=> Adding string tests

cHelpers.go, oci8.go.h, oci8SqlString_test.go, oci8Sql_test.go, oci8_test.go, rows.go, statement.go
After https://github.com/mattn/go-oci8/pull/281
=> Added and removed helpers

README.md, connection.go, exampleSql_test.go, globals.go, oci8.go, oci8.go.h, oci8SqlNumber_test.go, oci8Sql_test.go, statement.go
After https://github.com/mattn/go-oci8/pull/286
=> Switch to new C helpers

connection.go, globals.go, more_test.go, oci8.go, oci8SqlString_test.go, oci8Sql_test.go, oci8_go18.go
After https://github.com/mattn/go-oci8/pull/291
=> Default character set to AL32UTF8

oci8.go, statement.go
prefetchRows checks for not default
questionph uses strconv.ParseBool
=> Updated ParseDSN comments

connection.go, oci8.go, oci8.go.h, rows.go
After https://github.com/mattn/go-oci8/pull/300
=> Converted wrappers to direct C #2

oci8.go, oci8Sql_test.go, oci8_test.go, statement.go
https://github.com/mattn/go-oci8/issues/38
=> Set default prefetchRows to 0 and prefetchMemory to 4096

oci8SqlString_test.go, test.sh
Added/updated non-English string tests
=> Updated testing to Go 1.11.4 & 1.10.7

connection.go, oci8.go
- OCI_SUCCESS_WITH_INFO was causing errors on pings
=> Handle OCI_SUCCESS_WITH_INFO on Pings

oci8_test.go
=> TestParseDSN switch to timeLocations

connection.go, exampleSql_test.go, oci8.go, oci8Sql_test.go, statement.go
@mattn Please review. Not able to create a good test case for this change.
Welcome to merge if change is good.
=> Add ociBreak to Ping

oci8.go
=> Added connection timeout doc note

globals.go, oci8.go
=> Removed unneeded externalauthentication

connection.go, globals.go, oci8SqlString_test.go, oci8_test.go, rows.go, statement.go
@mattn 
Please review and merge
=> Fix LOB > 32767 for insert/update

globals.go, more_test.go, oci8_sql_number_test.go, oci8_sql_string_test.go, oci8_sql_time_test.go, rows.go, statement.go
@mattn Please review and merge
=> Columns fixes and tests

oci8_sql_number_test.go, oci8_sql_string_test.go, oci8_sql_time_test.go, rows.go
@mattn Please review, merge, and add release 0.0.3.
Note that ColumnTypeNullable was remove because is a OCI_ATTR_IS_NULL is an OCIDescribeAny function which requires additional setup/code to use. As it was previously coded it was always returning false, false. Welcome to add it back in later with OCIDescribeAny code if still wanted.
=> Updated ColumnTypeLength

connector.go, more_test.go, oci8_sql_test.go
@mattn Please review and merge
=> Updated TestQuestionMark

example_sql_test.go
=> Updated Example_sqlSelect example

statement.go
@mattn Please review and merge
=> Fix query - freeDefines

connection.go, globals.go, rows.go, statement.go
@mattn Please review and merge
=> Switched to OCIStmtPrepare2 & Improve context done

test.sh, test_cleanup.sh
=> Update go 1.13 revision, add 1.14 and 1.15 versions as tests harnesses
