more_test.go, oci8.go
TestTime1() and TestTime2() were failing, due to silent failure of time zone parsing by oracle.
In particular, for TestTime1(), line 728, "zone, offset" := t.Zone()" sets zone="EDT"
C.OCIDateTimeConstruct(), on line 752, returns C.OCI_SUCCESS for "EDT" but treats it as UTC. :(
I see the same behavior with many other three letter time zones.
Since it returned C.OCI_SUCCESS the fall back code in the for loop (lines 771-778) isn't tried.
So I swapped the scenarios.  Now the offset logic (lines 771-779) is tried first.
I added a test for all time zones that go knows about, and they all work for me.
FWIW:
go 1.4.2, Debian 7/Wheezy, amd64.
Oracle client lib 10.1.0.5
Oracle Database 10g Enterprise Edition Release 10.1.0.4.0 - 64bi
Oracle Database 11g Enterprise Edition Release 11.2.0.4.0 - 64bit …
=> Fix timezone handling.

oci8.go
I faced the `ORA-01406 fetched column value was truncated` error when querying a column with a NUMBER type with many decimal digits.
That was solved by increasing the size of `lp` variable under `C.SQLT_NUM`.
What do you think?
=> Increased NUMBER type buffer size

more_test.go, oci8.go
From Oracle Call Interface Programmer's Guide:
> The OCI will deallocate a child handle if the parent is deallocated.
=> fix race condition in OCI8Conn.Close

README.md
I took same time to find that `-loci` is Windows specific, and one should use `-lclntsh` to be able to compile on Linux.
=> Add oci8.pc example for Linux on README

oci8.go
Most Oracle database errors can be handled farther up in the problem but disconnected connections can not be handled. If you have a pool of connections and any one of the connections gets terminated or disconnected, the only way to reconnect is to close down all the connections and then reconnect. The GoLang sql package provides automatic reconnect but only if you pass up the driver.ErrBadConn error. So this change will let the GoLang sql package handle the reconnects on database disconnected or user not logged in, which is errors ORA-03114 and ORA-01012.
=> Added driver.ErrBadConn for disconnect

oci8.go
all the other error paths also freed the bound parameters.
=> Fix a possible memory leakage

oci8.go
When running db.Exec many times (approx 300 on Vagrant Test VM with oracle xe 11.2 ) within a single program, the "ORA-01000: maximum open cursors exceeded" is thrown.
=> Defered Close instruction on prepared statement

oci8.go
Added deferred close to prepared statement in query method to prevent same issue as fixed in #130
=> deferred close on prepared statement in query method

oci8.go, oci8_test.go
`ORA-03113` is also a bad connection;
> The ORA-03113 error when connecting suggests that the connection was established, but lost later, like a timeout. 
more [detail](http://dba-oracle.com/m_ora_03113_end_of_file_on_communications_channel.htm)
=> feat: add `ORA-03113` to bad connection

oci8.go, oci8_go18.go
This pull request avoids  runtime.SetFinalizer calls and thus avoids potential problems such as "A finalizer may run as soon as an object becomes unreachable" ...
=> Avoid runtime.SetFinalizer to close statements

oci8.go
Adding the privilege 'sysasm' by name in order to be compliant with the
sqlplus client side. In the connect itself, you can also connect with
'sysdba' to an ASM instance, the OCI8 layer will handle this correctly.
=> Allow connection to an ASM instance with sysasm

more_test.go, oci8.go
hi all,
what i get  is all column type is []string
easy to reproduce such issue, just print all column ScanType when exec sql  to oracle;
codes below are copied form func ColumnTypeDatabaseTypeName, and it works eventally
```
rp := C.WrapOCIParamGet(rc.s.s, C.OCI_HTYPE_STMT, (*C.OCIError)(rc.s.c.err), C.ub4(i+1))
if rp.rv == C.OCI_SUCCESS {
p = rp.ptr
}
```
thanks for your time
=> Seem issue on func ColumnTypeScanType, all ScanType we get is []string

oci8.go
Ping() fails against a legacy Oracle 8i database.
However, OCIPing returns an error of "ORA-01010: invalid OCI operation", thus confirming that the connection is active.
A similar fix can be found at https://github.com/rana/ora/issues/224
=> Fix Ping() for older versions of Oracle (<10.2?)

statement.go
https://github.com/mattn/go-oci8/issues/306
=> Double max size buffer for strings

oci8.go
I refer to the qt source code package oci part（version: 4.8.5  file: qsql_oci.cpp  line: 2221）, it should be like this. And the previous if result != C.OCI_SUCCESS || result == C.OCI_SUCCESS_WITH_INFO does not conform to normal logic
=> fix bug: return value OCI_SUCCESS_WITH_INFO

statement.go
(Let Oracle OCI driver do the named parameter checks)
=> Allow multiple time use of single named parameter

oci8.go
I recently updated this module and had a curious error message.
`
Invalid questionpm: YES
`
I understand that `questionph=YES` is now invalid because this is using strconv.ParseBool. That is fine.
The error message should match the option name that is passed.
=> questionph: error msg match option

connection.go, globals.go, oci8.go, oci8_sql_go_113_test.go, oci8_sql_string_test.go, oci8_sql_test.go, oci8_test.go, rows.go, statement.go, test.sh
- added parameter `stmt_cache_size` to DSN string. Defaults to zero, disabled. When enabled, it sets the `OCI_ATTR_STMTCACHESIZE` attribute.
- when enabled, passes the query in as the key to `OCIStmtPrepare2`, and also passes the same key to `OCIStmtRelease`. Note that the Java OCI driver uses the query as the cache key as well, hence my choice of using it.
- bumped up the number of processes and sessions in the `test.sh` because it was consistently running out of connections
- also fixed sporadic failures of test for `ORA-01013` but changing to a `!string.Contains` check
=> Added Statement caching

statement.go
We believe this PR can fix #405 .
It frees OCI row id descriptor via`OCIDescriptorFree` in`getRowid()`
=> Fix a memory leakage in getRowid

connection.go, globals.go, oci8.go, oci8_sql_test.go
Transaction handles are currently allocated upon starting new transactions without proper deallocations of previous handles, which leads to memory leaks. This PR fixes this issue following an approach seen in other OCI driver implementations: a single transaction handle is reused for every new transaction.
**Note**: somehow, one test case (`TestSelectDualString`) seems to have a non-deterministic behavior, as it might occasionally fail even in the `master` branch. All other tests passed normally. We also tested this fix under realistic loads in one of our apps and everything ran smoothly.
=> Fix: memory leak in transaction handles
